server:
  port: 3020

spring:
  dubbo:
    application:
      name: sp-web
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.bnq.supplier

logging:
  file: ${user.home}/logs/sp-web.log